package:
  name: commute
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  script_env:
    - VERSION
    - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
  run:
    - scipy
    - pyprind
    - pandas
    - xarray
    - numpy
    - klausen
    - xlrd
    - numexpr
    - bw2io
    - pycountry
    - wurst
    - pyyaml

test:
  imports:
    - commute

about:
  home: https://github.com/romainsacchi/commute
  license: BSD License
  summary: 'Life Cycle Assessment for passenger and freight transport.'
license_family: BSD